Improve GitLab support
plone/cookieplone-templates pull request #66
Opened 2024-10-10 06:49 UTC by erral

With this PR I bring back GitLab CI/CD support with the following features:

Add a question whether to use GitLab based deployment. If so, add a `.gitlab-ci.yml` file that will add the required job pipelines which check, test, build, release and deploy the containers.

I have slightly changed the generated docker image names *only when GitLab deployment is enabled* because of GitLab peculiarities: in a single GitLab repo you can save different docker files, but their name must match the structure gitlab_url/gitlab_username/project_slug/docker_image/variant so, instead of having *registry.gitlab.com/codesyntax/project-backend* we are having *registry.gitlab.com/codesyntax/project/backend* (- vs. /)

2024-11-05 22:26 UTC, davisagli commented
@erral What's the status of this one? I'd like to include it, but I can't easily test it myself.

2024-11-06 06:37 UTC, erral commented
I am polishing the configuration file and doing some more tests.

I want to finish this later this week.

2024-11-08 16:01 UTC, erral commented
@stevepiercy can you review the documentation I added in the `README_GITLAB.md` file please?

2024-11-08 16:15 UTC, erral commented
I have tested this on gitlab, with the following result:

![2024-11-08 17-14-46](https://github.com/user-attachments/assets/9ec1a8c4-8bde-4344-9490-642c2d7e050e)

2024-11-08 19:50 UTC, stevepiercy requested changes
Some grammar fixes, GitHub Markdown syntax flavoring, and a few questions. Otherwise docs look good.

2024-11-08 19:50 UTC, stevepiercy commented on project/cookiecutter.json
> +      "__prompt__": "Add GitLab Action to Deploy this project?",
I found no term "GitLab Action". It appears they call it the inelegant, yet accurate, mouthful "GitLab CI/CD". Also lower case "deploy". Please replace all instances of both.

```suggestion
      "__prompt__": "Add GitLab CI/CD to deploy this project?",
```

2024-11-08 19:50 UTC, stevepiercy commented on project/hooks/post_gen_project.py
> +            "Remove GHA deployment files",
The naming is confusing. The handle says remove gitlab, but the message says remove github actions (GHA).

2024-11-08 19:50 UTC, stevepiercy commented on project/{{ cookiecutter.__folder_name }}/devops/README-GITLAB.md
> +[Register a runner](https://docs.gitlab.com/runner/register/) in one of your servers, and then modify its configuration (check `/etc/gitlab-runner/config.toml`):
```suggestion
[Register a runner](https://docs.gitlab.com/runner/register/) in one of your servers.
Then modify its configuration file `/etc/gitlab-runner/config.toml` as needed.
```

2024-11-08 19:50 UTC, stevepiercy commented on project/{{ cookiecutter.__folder_name }}/devops/README-GITLAB.md
> +    **Note**: do not mark any of the variables as *protected*.
Let's try an admonition. https://github.com/orgs/community/discussions/16925

```suggestion
    > [!NOTE]
    > Do not mark any of the variables as *protected*.
```

2024-11-08 19:50 UTC, stevepiercy commented on project/{{ cookiecutter.__folder_name }}/devops/README-GITLAB.md
> +## Development & deployment 🚀
```suggestion
## Development and deployment 🚀
```

2024-11-08 19:50 UTC, stevepiercy commented on project/{{ cookiecutter.__folder_name }}/devops/README-GITLAB.md
> +The development should be done in a separate branch such as `develop`.
```suggestion
Development should be done in a separate branch, such as `develop`.
```

2024-11-08 19:50 UTC, stevepiercy commented on project/{{ cookiecutter.__folder_name }}/devops/README-GITLAB.md
> +When opening a merge requests from that branch to `main`, the checks and tests will be executed and docker images
Please verify that the pipeline logic in this sentence is correct. I assume that if either checks or tests fail, then the Docker images will not be built.

```suggestion
When opening a merge request from your development branch to `main`, CI/CD runs the checks and tests, and, if they pass, then builds the Docker images.
```

2024-11-08 19:50 UTC, stevepiercy commented on project/{{ cookiecutter.__folder_name }}/devops/README-GITLAB.md
> +will be built.
Merged into previous sentence.

```suggestion
```

2024-11-11 08:42 UTC, stevepiercy approved these changes
Docs and comments LGTM. Needs a technical review. Thank you!

2024-11-13 20:05 UTC, ericof commented
@erral Could you sync this with the main branch?

2024-11-13 20:14 UTC, erral commented
> @erral Could you sync this with the main branch?

done!

2025-01-14 23:42 UTC, davisagli reviewed
It's a bit messy to need conditional logic for the image names everywhere they are used. Is it possible to include the dash or slash in `__container_image_prefix`?

2025-02-17 10:50 UTC, erral commented
> It's a bit messy to need conditional logic for the image names everywhere they are used. Is it possible to include the dash or slash in `__container_image_prefix`?

I have revisited this: I have created a new entry for the separator, and the corresponding filter in cookieplone (see https://github.com/plone/cookieplone/pull/68) to create it.

2025-04-05 07:01 UTC, closed without merging

2025-04-05 07:06 UTC, erral commented
I am closing this because it needs some work to make it work after the template restructuring.