use local env_vars and not remove server's one
plone/cookieplone-templates pull request #70
Opened 2024-10-14 07:14 UTC by erral

With my previouse changes we were using env vars present in the remote server instead of the ones present in the local .env file.

2024-10-15 21:44 UTC, davisagli requested changes

2024-10-15 21:44 UTC, davisagli commented on project/{{ cookiecutter.__folder_name }}/devops/inventory/group_vars/all/projects.yml
> +  - path: "{{ lookup('env', 'DEPLOY_FOLDER', default='/srv/plone/data') }}"
Removing the dash doesn't look right to me. `project_folders` is used as a list here: https://github.com/plone/cookieplone-templates/blob/185dfb4f6589c60b522cb6cd7c06397be0d64710/project/%7B%7B%20cookiecutter.__folder_name%20%7D%7D/devops/playbooks/setup.yml#L134

2024-10-16 15:29 UTC, davisagli commented on project/{{ cookiecutter.__folder_name }}/devops/inventory/group_vars/all/projects.yml
> +  - path: "{{ lookup('env', 'DEPLOY_FOLDER', default='/srv/plone/data') }}"
@erral Okay, thanks for testing it!

2024-10-30 05:57 UTC, erral commented
Superceeded by latest merged PRs by Érico

2024-10-30 05:57 UTC, closed without merging