Rename Makefile targets following cookiecutter-volto#14
plone/cookieplone-templates pull request #9
Opened 2024-05-14 17:05 UTC by sneridagh

2024-05-14 20:24 UTC, stevepiercy requested changes
Looks great. However a new pattern emerged with `ci-*` targets, which needs agreement.

I also added the new `ci-acceptance-backend-start` target to https://github.com/plone/cookiecutter-volto/issues/14#issuecomment-2068663318. This addition established the `ci-*` pattern for targets.

2024-05-14 20:24 UTC, stevepiercy commented on frontend_addon/{{ cookiecutter.__folder_name }}/Makefile
> +ci-acceptance-backend-start: ## Start acceptance server in CI (no terminal attached)
```suggestion
ci-acceptance-backend-start: ## Start backend acceptance server in headless mode for CI
```

I also added this to https://github.com/plone/cookiecutter-volto/issues/14#issuecomment-2068663318

2024-05-14 20:24 UTC, stevepiercy commented on frontend_addon/{{ cookiecutter.__folder_name }}/Makefile
> +.PHONY: acceptance-headless-test
For discussion: should we rename this to be consistent with the other two `ci-*` targets?

```suggestion
.PHONY: ci-acceptance-test
```

2024-05-14 20:24 UTC, stevepiercy commented on frontend_addon/{{ cookiecutter.__folder_name }}/Makefile
> +acceptance-headless-test: ## Run cypress tests in headless mode for CI
See previous comment.

```suggestion
ci-acceptance-test: ## Run cypress tests in headless mode for CI
```

2024-05-14 20:24 UTC, stevepiercy commented on frontend_addon/{{ cookiecutter.__folder_name }}/Makefile
> +ci-acceptance-backend-start: ## Start acceptance server in CI (no terminal attached)
Note I used "headless mode" in the target's description for consistency with other `ci-*` targets.

2024-05-15 13:06 UTC, sneridagh commented
@stevepiercy done!

2024-05-15 13:51 UTC, merged